### ISSUE TITLE
Problem after merge

### ISSUE THREAD

**Issue by ThalesACarvalho** [ThalesACarvalho/evolution-api#5]
After the merge of the last issue I got this error:

✔ Generated Prisma Client (v6.8.1) to ./node_modules/@prisma/client in 490ms

Start by importing your Prisma Client (See: https://pris.ly/d/importing-client)

Tip: Interested in query caching in just a few lines of code? Try Accelerate today! https://pris.ly/tip-3-accelerate

Prisma generate succeeded

[builder 15/16] RUN ./Docker/scripts/generate_database.sh  ✔ 4 sec

[builder 16/16] RUN npm run build

> evolution-api@2.3.0 build
> tsc --noEmit && tsup

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts(693,23): error TS2339: Property 'connectingStartTime' does not exist on type 'Instance'.

src/api/integrations/channel/whatsapp/whatsapp.baileys.service.ts(703,91): error TS2554: Expected 1 arguments, but got 2.

src/api/services/connection-health.service.ts(47,49): error TS2554: Expected 1 arguments, but got 2.
src/api/services/connection-health.service.ts(89,78): error TS2554: Expected 1 arguments, but got 2.

src/api/services/connection-health.service.ts(116,66): error TS2554: Expected 1 arguments, but got 2.

src/api/services/connection-health.service.ts(132,86): error TS2554: Expected 1 arguments, but got 2.

src/api/services/connection-health.service.ts(150,85): error TS2554: Expected 1 arguments, but got 2.
src/api/services/connection-health.service.ts(171,85): error TS2554: Expected 1 arguments, but got 2.
src/api/services/connection-health.service.ts(188,79): error TS2554: Expected 1 arguments, but got 2.

src/api/services/connection-health.service.ts(196,81): error TS2554: Expected 1 arguments, but got 2.

src/api/services/graceful-shutdown.service.ts(61,60): error TS2554: Expected 1 arguments, but got 2.

src/api/services/graceful-shutdown.service.ts(92,68): error TS2554: Expected 1 arguments, but got 2.

src/api/services/graceful-shutdown.service.ts(124,83): error TS2554: Expected 1 arguments, but got 2.

src/api/services/graceful-shutdown.service.ts(132,60): error TS2554: Expected 1 arguments, but got 2.

src/api/services/graceful-shutdown.service.ts(153,89): error TS2554: Expected 1 arguments, but got 2.
src/api/services/graceful-shutdown.service.ts(161,57): error TS2554: Expected 1 arguments, but got 2.
src/api/services/graceful-shutdown.service.ts(196,84): error TS2554: Expected 1 arguments, but got 2.

src/api/services/graceful-shutdown.service.ts(217,58): error TS2554: Expected 1 arguments, but got 2.

src/api/services/monitor.service.ts(232,53): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(55,56): error TS2554: Expected 1 arguments, but got 2.
src/api/services/session-restoration.service.ts(80,82): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(88,64): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(127,13): error TS2322: Type '{ enabled: true; url: string; events: string | number | true | JsonObject | JsonArray; byEvents: any; base64: any; }' is not assignable to type '{ enabled?: boolean; events?: string[]; headers?: JsonValue; url?: string; byEvents?: boolean; base64?: boolean; }'.
  Types of property 'events' are incompatible.
    Type 'string | number | true | JsonObject | JsonArray' is not assignable to type 'string[]'.
      Type 'string' is not assignable to type 'string[]'.

src/api/services/session-restoration.service.ts(131,42): error TS2551: Property 'byEvents' does not exist on type '{ enabled: boolean; instanceId: string; url: string; id: string; createdAt: Date; updatedAt: Date; headers: JsonValue; events: JsonValue; webhookByEvents: boolean; webhookBase64: boolean; }'. Did you mean 'events'?
src/api/services/session-restoration.service.ts(132,40): error TS2339: Property 'base64' does not exist on type '{ enabled: boolean; instanceId: string; url: string; id: string; createdAt: Date; updatedAt: Date; headers: JsonValue; events: JsonValue; webhookByEvents: boolean; webhookBase64: boolean; }'.

src/api/services/session-restoration.service.ts(158,77): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(166,61): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(178,67): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(206,85): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(228,67): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(259,77): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(272,74): error TS2554: Expected 1 arguments, but got 2.
src/api/services/session-restoration.service.ts(301,82): error TS2554: Expected 1 arguments, but got 2.

src/api/services/session-restoration.service.ts(320,81): error TS2554: Expected 1 arguments, but got 2.
src/main.ts(34,62): error TS2554: Expected 1 arguments, but got 2.

✕ [builder 16/16] RUN npm run build 
process "/bin/sh -c npm run build" did not complete successfully: exit code: 2
 

Dockerfile:29

-------------------

27 |     RUN ./Docker/scripts/generate_database.sh

28 |

29 | >>> RUN npm run build

30 |

31 |     FROM node:20-alpine AS final

-------------------

ERROR: failed to build: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 2
